# This file should contain all the record creation needed
# to seed the database with its default values.
# The data can then be loaded with the rails db:seed command
# (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

regions = Region.create([
    {zip_code: '01001', name: 'Hampden'},
    {zip_code: '01002', name: 'Hampshire'},
    {zip_code: '01003', name: 'Hampshire'},
    {zip_code: '01004', name: 'Hampshire'},
    {zip_code: '01005', name: 'Worcester'},
    {zip_code: '01007', name: 'Hampshire'},
    {zip_code: '01008', name: 'Hampden'},
    {zip_code: '01009', name: 'Hampden'},
    {zip_code: '01010', name: 'Hampden'},
    {zip_code: '01011', name: 'Hampden'},
    {zip_code: '01012', name: 'Hampshire'},
    {zip_code: '01013', name: 'Hampden'},
    {zip_code: '01014', name: 'Hampden'},
    {zip_code: '01020', name: 'Hampden'},
    {zip_code: '01021', name: 'Hampden'},
    {zip_code: '01022', name: 'Hampden'},
    {zip_code: '01026', name: 'Hampshire'},
    {zip_code: '01027', name: 'Hampshire'},
    {zip_code: '01028', name: 'Hampden'},
    {zip_code: '01029', name: 'Berkshire'},
    {zip_code: '01030', name: 'Hampden'},
    {zip_code: '01031', name: 'Worcester'},
    {zip_code: '01032', name: 'Hampshire'},
    {zip_code: '01033', name: 'Hampshire'},
    {zip_code: '01034', name: 'Hampden'},
    {zip_code: '01035', name: 'Hampshire'},
    {zip_code: '01036', name: 'Hampden'},
    {zip_code: '01037', name: 'Worcester'},
    {zip_code: '01038', name: 'Hampshire'},
    {zip_code: '01039', name: 'Hampshire'},
    {zip_code: '01040', name: 'Hampden'},
    {zip_code: '01041', name: 'Hampden'},
    {zip_code: '01050', name: 'Hampshire'},
    {zip_code: '01053', name: 'Hampshire'},
    {zip_code: '01054', name: 'Franklin'},
    {zip_code: '01056', name: 'Hampden'},
    {zip_code: '01057', name: 'Hampden'},
    {zip_code: '01059', name: 'Hampshire'},
    {zip_code: '01060', name: 'Hampshire'},
    {zip_code: '01061', name: 'Hampshire'},
    {zip_code: '01062', name: 'Hampshire'},
    {zip_code: '01063', name: 'Hampshire'},
    {zip_code: '01066', name: 'Hampshire'},
    {zip_code: '01068', name: 'Worcester'},
    {zip_code: '01069', name: 'Hampden'},
    {zip_code: '01070', name: 'Hampshire'},
    {zip_code: '01071', name: 'Hampden'},
    {zip_code: '01072', name: 'Franklin'},
    {zip_code: '01073', name: 'Hampshire'},
    {zip_code: '01074', name: 'Worcester'},
    {zip_code: '01075', name: 'Hampshire'},
    {zip_code: '01077', name: 'Hampden'},
    {zip_code: '01079', name: 'Hampden'},
    {zip_code: '01080', name: 'Hampden'},
    {zip_code: '01081', name: 'Hampden'},
    {zip_code: '01082', name: 'Hampshire'},
    {zip_code: '01083', name: 'Worcester'},
    {zip_code: '01084', name: 'Hampshire'},
    {zip_code: '01085', name: 'Hampden'},
    {zip_code: '01086', name: 'Hampden'},
    {zip_code: '01088', name: 'Hampshire'},
    {zip_code: '01089', name: 'Hampden'},
    {zip_code: '01090', name: 'Hampden'},
    {zip_code: '01092', name: 'Worcester'},
    {zip_code: '01093', name: 'Franklin'},
    {zip_code: '01094', name: 'Worcester'},
    {zip_code: '01095', name: 'Hampden'},
    {zip_code: '01096', name: 'Hampshire'},
    {zip_code: '01097', name: 'Hampden'},
    {zip_code: '01098', name: 'Hampshire'},
    {zip_code: '01101', name: 'Hampden'},
    {zip_code: '01102', name: 'Hampden'},
    {zip_code: '01103', name: 'Hampden'},
    {zip_code: '01104', name: 'Hampden'},
    {zip_code: '01105', name: 'Hampden'},
    {zip_code: '01106', name: 'Hampden'},
    {zip_code: '01107', name: 'Hampden'},
    {zip_code: '01108', name: 'Hampden'},
    {zip_code: '01109', name: 'Hampden'},
    {zip_code: '01111', name: 'Hampden'},
    {zip_code: '01115', name: 'Hampden'},
    {zip_code: '01116', name: 'Hampden'},
    {zip_code: '01118', name: 'Hampden'},
    {zip_code: '01119', name: 'Hampden'},
    {zip_code: '01128', name: 'Hampden'},
    {zip_code: '01129', name: 'Hampden'},
    {zip_code: '01138', name: 'Hampden'},
    {zip_code: '01139', name: 'Hampden'},
    {zip_code: '01144', name: 'Hampden'},
    {zip_code: '01151', name: 'Hampden'},
    {zip_code: '01152', name: 'Hampden'},
    {zip_code: '01199', name: 'Hampden'},
    {zip_code: '01201', name: 'Berkshire'},
    {zip_code: '01202', name: 'Berkshire'},
    {zip_code: '01203', name: 'Berkshire'},
    {zip_code: '01220', name: 'Berkshire'},
    {zip_code: '01222', name: 'Berkshire'},
    {zip_code: '01223', name: 'Berkshire'},
    {zip_code: '01224', name: 'Berkshire'},
    {zip_code: '01225', name: 'Berkshire'},
    {zip_code: '01226', name: 'Berkshire'},
    {zip_code: '01227', name: 'Berkshire'},
    {zip_code: '01229', name: 'Berkshire'},
    {zip_code: '01230', name: 'Berkshire'},
    {zip_code: '01235', name: 'Berkshire'},
    {zip_code: '01236', name: 'Berkshire'},
    {zip_code: '01237', name: 'Berkshire'},
    {zip_code: '01238', name: 'Berkshire'},
    {zip_code: '01240', name: 'Berkshire'},
    {zip_code: '01242', name: 'Berkshire'},
    {zip_code: '01243', name: 'Hampshire'},
    {zip_code: '01244', name: 'Berkshire'},
    {zip_code: '01245', name: 'Berkshire'},
    {zip_code: '01247', name: 'Berkshire'},
    {zip_code: '01252', name: 'Berkshire'},
    {zip_code: '01253', name: 'Berkshire'},
    {zip_code: '01254', name: 'Berkshire'},
    {zip_code: '01255', name: 'Berkshire'},
    {zip_code: '01256', name: 'Berkshire'},
    {zip_code: '01257', name: 'Berkshire'},
    {zip_code: '01258', name: 'Berkshire'},
    {zip_code: '01259', name: 'Berkshire'},
    {zip_code: '01260', name: 'Berkshire'},
    {zip_code: '01262', name: 'Berkshire'},
    {zip_code: '01263', name: 'Berkshire'},
    {zip_code: '01264', name: 'Berkshire'},
    {zip_code: '01266', name: 'Berkshire'},
    {zip_code: '01267', name: 'Berkshire'},
    {zip_code: '01270', name: 'Berkshire'},
    {zip_code: '01301', name: 'Franklin'},
    {zip_code: '01302', name: 'Franklin'},
    {zip_code: '01330', name: 'Franklin'},
    {zip_code: '01331', name: 'Worcester'},
    {zip_code: '01337', name: 'Franklin'},
    {zip_code: '01338', name: 'Franklin'},
    {zip_code: '01339', name: 'Franklin'},
    {zip_code: '01340', name: 'Franklin'},
    {zip_code: '01341', name: 'Franklin'},
    {zip_code: '01342', name: 'Franklin'},
    {zip_code: '01343', name: 'Berkshire'},
    {zip_code: '01344', name: 'Franklin'},
    {zip_code: '01346', name: 'Franklin'},
    {zip_code: '01347', name: 'Franklin'},
    {zip_code: '01349', name: 'Franklin'},
    {zip_code: '01350', name: 'Franklin'},
    {zip_code: '01351', name: 'Franklin'},
    {zip_code: '01354', name: 'Franklin'},
    {zip_code: '01355', name: 'Franklin'},
    {zip_code: '01360', name: 'Franklin'},
    {zip_code: '01364', name: 'Franklin'},
    {zip_code: '01366', name: 'Worcester'},
    {zip_code: '01367', name: 'Franklin'},
    {zip_code: '01368', name: 'Worcester'},
    {zip_code: '01370', name: 'Franklin'},
    {zip_code: '01373', name: 'Franklin'},
    {zip_code: '01375', name: 'Franklin'},
    {zip_code: '01376', name: 'Franklin'},
    {zip_code: '01378', name: 'Franklin'},
    {zip_code: '01379', name: 'Franklin'},
    {zip_code: '01380', name: 'Franklin'},
    {zip_code: '01420', name: 'Worcester'},
    {zip_code: '01430', name: 'Worcester'},
    {zip_code: '01431', name: 'Middlesex'},
    {zip_code: '01432', name: 'Middlesex'},
    {zip_code: '01434', name: 'Worcester'},
    {zip_code: '01436', name: 'Worcester'},
    {zip_code: '01438', name: 'Worcester'},
    {zip_code: '01440', name: 'Worcester'},
    {zip_code: '01441', name: 'Worcester'},
    {zip_code: '01450', name: 'Middlesex'},
    {zip_code: '01451', name: 'Worcester'},
    {zip_code: '01452', name: 'Worcester'},
    {zip_code: '01453', name: 'Worcester'},
    {zip_code: '01460', name: 'Middlesex'},
    {zip_code: '01462', name: 'Worcester'},
    {zip_code: '01463', name: 'Middlesex'},
    {zip_code: '01464', name: 'Middlesex'},
    {zip_code: '01467', name: 'Worcester'},
    {zip_code: '01468', name: 'Worcester'},
    {zip_code: '01469', name: 'Middlesex'},
    {zip_code: '01470', name: 'Middlesex'},
    {zip_code: '01471', name: 'Middlesex'},
    {zip_code: '01472', name: 'Middlesex'},
    {zip_code: '01473', name: 'Worcester'},
    {zip_code: '01474', name: 'Middlesex'},
    {zip_code: '01475', name: 'Worcester'},
    {zip_code: '01501', name: 'Worcester'},
    {zip_code: '01503', name: 'Worcester'},
    {zip_code: '01504', name: 'Worcester'},
    {zip_code: '01505', name: 'Worcester'},
    {zip_code: '01506', name: 'Worcester'},
    {zip_code: '01507', name: 'Worcester'},
    {zip_code: '01508', name: 'Worcester'},
    {zip_code: '01509', name: 'Worcester'},
    {zip_code: '01510', name: 'Worcester'},
    {zip_code: '01515', name: 'Worcester'},
    {zip_code: '01516', name: 'Worcester'},
    {zip_code: '01518', name: 'Worcester'},
    {zip_code: '01519', name: 'Worcester'},
    {zip_code: '01520', name: 'Worcester'},
    {zip_code: '01521', name: 'Hampden'},
    {zip_code: '01522', name: 'Worcester'},
    {zip_code: '01523', name: 'Worcester'},
    {zip_code: '01524', name: 'Worcester'},
    {zip_code: '01525', name: 'Worcester'},
    {zip_code: '01526', name: 'Worcester'},
    {zip_code: '01527', name: 'Worcester'},
    {zip_code: '01529', name: 'Worcester'},
    {zip_code: '01531', name: 'Worcester'},
    {zip_code: '01532', name: 'Worcester'},
    {zip_code: '01534', name: 'Worcester'},
    {zip_code: '01535', name: 'Worcester'},
    {zip_code: '01536', name: 'Worcester'},
    {zip_code: '01537', name: 'Worcester'},
    {zip_code: '01538', name: 'Worcester'},
    {zip_code: '01540', name: 'Worcester'},
    {zip_code: '01541', name: 'Worcester'},
    {zip_code: '01542', name: 'Worcester'},
    {zip_code: '01543', name: 'Worcester'},
    {zip_code: '01545', name: 'Worcester'},
    {zip_code: '01546', name: 'Worcester'},
    {zip_code: '01550', name: 'Worcester'},
    {zip_code: '01560', name: 'Worcester'},
    {zip_code: '01561', name: 'Worcester'},
    {zip_code: '01562', name: 'Worcester'},
    {zip_code: '01564', name: 'Worcester'},
    {zip_code: '01566', name: 'Worcester'},
    {zip_code: '01568', name: 'Worcester'},
    {zip_code: '01569', name: 'Worcester'},
    {zip_code: '01570', name: 'Worcester'},
    {zip_code: '01571', name: 'Worcester'},
    {zip_code: '01581', name: 'Worcester'},
    {zip_code: '01583', name: 'Worcester'},
    {zip_code: '01585', name: 'Worcester'},
    {zip_code: '01586', name: 'Worcester'},
    {zip_code: '01588', name: 'Worcester'},
    {zip_code: '01590', name: 'Worcester'},
    {zip_code: '01601', name: 'Worcester'},
    {zip_code: '01602', name: 'Worcester'},
    {zip_code: '01603', name: 'Worcester'},
    {zip_code: '01604', name: 'Worcester'},
    {zip_code: '01605', name: 'Worcester'},
    {zip_code: '01606', name: 'Worcester'},
    {zip_code: '01607', name: 'Worcester'},
    {zip_code: '01608', name: 'Worcester'},
    {zip_code: '01609', name: 'Worcester'},
    {zip_code: '01610', name: 'Worcester'},
    {zip_code: '01611', name: 'Worcester'},
    {zip_code: '01612', name: 'Worcester'},
    {zip_code: '01613', name: 'Worcester'},
    {zip_code: '01614', name: 'Worcester'},
    {zip_code: '01615', name: 'Worcester'},
    {zip_code: '01653', name: 'Worcester'},
    {zip_code: '01655', name: 'Worcester'},
    {zip_code: '01701', name: 'Middlesex'},
    {zip_code: '01702', name: 'Middlesex'},
    {zip_code: '01703', name: 'Middlesex'},
    {zip_code: '01704', name: 'Middlesex'},
    {zip_code: '01705', name: 'Middlesex'},
    {zip_code: '01718', name: 'Middlesex'},
    {zip_code: '01719', name: 'Middlesex'},
    {zip_code: '01720', name: 'Middlesex'},
    {zip_code: '01721', name: 'Middlesex'},
    {zip_code: '01730', name: 'Middlesex'},
    {zip_code: '01731', name: 'Middlesex'},
    {zip_code: '01740', name: 'Worcester'},
    {zip_code: '01741', name: 'Middlesex'},
    {zip_code: '01742', name: 'Middlesex'},
    {zip_code: '01745', name: 'Worcester'},
    {zip_code: '01746', name: 'Middlesex'},
    {zip_code: '01747', name: 'Worcester'},
    {zip_code: '01748', name: 'Middlesex'},
    {zip_code: '01749', name: 'Middlesex'},
    {zip_code: '01752', name: 'Middlesex'},
    {zip_code: '01754', name: 'Middlesex'},
    {zip_code: '01756', name: 'Worcester'},
    {zip_code: '01757', name: 'Worcester'},
    {zip_code: '01760', name: 'Middlesex'},
    {zip_code: '01770', name: 'Middlesex'},
    {zip_code: '01772', name: 'Worcester'},
    {zip_code: '01773', name: 'Middlesex'},
    {zip_code: '01775', name: 'Middlesex'},
    {zip_code: '01776', name: 'Middlesex'},
    {zip_code: '01778', name: 'Middlesex'},
    {zip_code: '01784', name: 'Middlesex'},
    {zip_code: '01801', name: 'Middlesex'},
    {zip_code: '01803', name: 'Middlesex'},
    {zip_code: '01805', name: 'Middlesex'},
    {zip_code: '01810', name: 'Essex'},
    {zip_code: '01812', name: 'Essex'},
    {zip_code: '01813', name: 'Middlesex'},
    {zip_code: '01815', name: 'Middlesex'},
    {zip_code: '01821', name: 'Middlesex'},
    {zip_code: '01822', name: 'Middlesex'},
    {zip_code: '01824', name: 'Middlesex'},
    {zip_code: '01826', name: 'Middlesex'},
    {zip_code: '01827', name: 'Middlesex'},
    {zip_code: '01830', name: 'Essex'},
    {zip_code: '01831', name: 'Essex'},
    {zip_code: '01832', name: 'Essex'},
    {zip_code: '01833', name: 'Essex'},
    {zip_code: '01834', name: 'Essex'},
    {zip_code: '01835', name: 'Essex'},
    {zip_code: '01840', name: 'Essex'},
    {zip_code: '01841', name: 'Essex'},
    {zip_code: '01842', name: 'Essex'},
    {zip_code: '01843', name: 'Essex'},
    {zip_code: '01844', name: 'Essex'},
    {zip_code: '01845', name: 'Essex'},
    {zip_code: '01850', name: 'Middlesex'},
    {zip_code: '01851', name: 'Middlesex'},
    {zip_code: '01852', name: 'Middlesex'},
    {zip_code: '01853', name: 'Middlesex'},
    {zip_code: '01854', name: 'Middlesex'},
    {zip_code: '01860', name: 'Essex'},
    {zip_code: '01862', name: 'Middlesex'},
    {zip_code: '01863', name: 'Middlesex'},
    {zip_code: '01864', name: 'Middlesex'},
    {zip_code: '01865', name: 'Middlesex'},
    {zip_code: '01866', name: 'Middlesex'},
    {zip_code: '01867', name: 'Middlesex'},
    {zip_code: '01876', name: 'Middlesex'},
    {zip_code: '01879', name: 'Middlesex'},
    {zip_code: '01880', name: 'Middlesex'},
    {zip_code: '01885', name: 'Essex'},
    {zip_code: '01886', name: 'Middlesex'},
    {zip_code: '01887', name: 'Middlesex'},
    {zip_code: '01888', name: 'Middlesex'},
    {zip_code: '01889', name: 'Middlesex'},
    {zip_code: '01890', name: 'Middlesex'},
    {zip_code: '01899', name: 'Essex'},
    {zip_code: '01901', name: 'Essex'},
    {zip_code: '01902', name: 'Essex'},
    {zip_code: '01903', name: 'Essex'},
    {zip_code: '01904', name: 'Essex'},
    {zip_code: '01905', name: 'Essex'},
    {zip_code: '01906', name: 'Essex'},
    {zip_code: '01907', name: 'Essex'},
    {zip_code: '01908', name: 'Essex'},
    {zip_code: '01910', name: 'Essex'},
    {zip_code: '01913', name: 'Essex'},
    {zip_code: '01915', name: 'Essex'},
    {zip_code: '01921', name: 'Essex'},
    {zip_code: '01922', name: 'Essex'},
    {zip_code: '01923', name: 'Essex'},
    {zip_code: '01929', name: 'Essex'},
    {zip_code: '01930', name: 'Essex'},
    {zip_code: '01931', name: 'Essex'},
    {zip_code: '01936', name: 'Essex'},
    {zip_code: '01937', name: 'Essex'},
    {zip_code: '01938', name: 'Essex'},
    {zip_code: '01940', name: 'Essex'},
    {zip_code: '01944', name: 'Essex'},
    {zip_code: '01945', name: 'Essex'},
    {zip_code: '01949', name: 'Essex'},
    {zip_code: '01950', name: 'Essex'},
    {zip_code: '01951', name: 'Essex'},
    {zip_code: '01952', name: 'Essex'},
    {zip_code: '01960', name: 'Essex'},
    {zip_code: '01961', name: 'Essex'},
    {zip_code: '01965', name: 'Essex'},
    {zip_code: '01966', name: 'Essex'},
    {zip_code: '01969', name: 'Essex'},
    {zip_code: '01970', name: 'Essex'},
    {zip_code: '01971', name: 'Essex'},
    {zip_code: '01982', name: 'Essex'},
    {zip_code: '01983', name: 'Essex'},
    {zip_code: '01984', name: 'Essex'},
    {zip_code: '01985', name: 'Essex'},
    {zip_code: '02018', name: 'Plymouth'},
    {zip_code: '02019', name: 'Norfolk'},
    {zip_code: '02020', name: 'Plymouth'},
    {zip_code: '02021', name: 'Norfolk'},
    {zip_code: '02025', name: 'Norfolk'},
    {zip_code: '02026', name: 'Norfolk'},
    {zip_code: '02027', name: 'Norfolk'},
    {zip_code: '02030', name: 'Norfolk'},
    {zip_code: '02032', name: 'Norfolk'},
    {zip_code: '02035', name: 'Norfolk'},
    {zip_code: '02038', name: 'Norfolk'},
    {zip_code: '02040', name: 'Plymouth'},
    {zip_code: '02041', name: 'Plymouth'},
    {zip_code: '02043', name: 'Plymouth'},
    {zip_code: '02044', name: 'Plymouth'},
    {zip_code: '02045', name: 'Plymouth'},
    {zip_code: '02047', name: 'Plymouth'},
    {zip_code: '02048', name: 'Bristol'},
    {zip_code: '02050', name: 'Plymouth'},
    {zip_code: '02051', name: 'Plymouth'},
    {zip_code: '02052', name: 'Norfolk'},
    {zip_code: '02053', name: 'Norfolk'},
    {zip_code: '02054', name: 'Norfolk'},
    {zip_code: '02055', name: 'Plymouth'},
    {zip_code: '02056', name: 'Norfolk'},
    {zip_code: '02059', name: 'Plymouth'},
    {zip_code: '02060', name: 'Plymouth'},
    {zip_code: '02061', name: 'Plymouth'},
    {zip_code: '02062', name: 'Norfolk'},
    {zip_code: '02065', name: 'Plymouth'},
    {zip_code: '02066', name: 'Plymouth'},
    {zip_code: '02067', name: 'Norfolk'},
    {zip_code: '02070', name: 'Norfolk'},
    {zip_code: '02071', name: 'Norfolk'},
    {zip_code: '02072', name: 'Norfolk'},
    {zip_code: '02081', name: 'Norfolk'},
    {zip_code: '02090', name: 'Norfolk'},
    {zip_code: '02093', name: 'Norfolk'},
    {zip_code: '02108', name: 'Suffolk'},
    {zip_code: '02109', name: 'Suffolk'},
    {zip_code: '02110', name: 'Suffolk'},
    {zip_code: '02111', name: 'Suffolk'},
    {zip_code: '02112', name: 'Suffolk'},
    {zip_code: '02113', name: 'Suffolk'},
    {zip_code: '02114', name: 'Suffolk'},
    {zip_code: '02115', name: 'Suffolk'},
    {zip_code: '02116', name: 'Suffolk'},
    {zip_code: '02117', name: 'Suffolk'},
    {zip_code: '02118', name: 'Suffolk'},
    {zip_code: '02119', name: 'Suffolk'},
    {zip_code: '02120', name: 'Suffolk'},
    {zip_code: '02121', name: 'Suffolk'},
    {zip_code: '02122', name: 'Suffolk'},
    {zip_code: '02123', name: 'Suffolk'},
    {zip_code: '02124', name: 'Suffolk'},
    {zip_code: '02125', name: 'Suffolk'},
    {zip_code: '02126', name: 'Suffolk'},
    {zip_code: '02127', name: 'Suffolk'},
    {zip_code: '02128', name: 'Suffolk'},
    {zip_code: '02129', name: 'Suffolk'},
    {zip_code: '02130', name: 'Suffolk'},
    {zip_code: '02131', name: 'Suffolk'},
    {zip_code: '02132', name: 'Suffolk'},
    {zip_code: '02133', name: 'Suffolk'},
    {zip_code: '02134', name: 'Suffolk'},
    {zip_code: '02135', name: 'Suffolk'},
    {zip_code: '02136', name: 'Suffolk'},
    {zip_code: '02137', name: 'Suffolk'},
    {zip_code: '02138', name: 'Middlesex'},
    {zip_code: '02139', name: 'Middlesex'},
    {zip_code: '02140', name: 'Middlesex'},
    {zip_code: '02141', name: 'Middlesex'},
    {zip_code: '02142', name: 'Middlesex'},
    {zip_code: '02143', name: 'Middlesex'},
    {zip_code: '02144', name: 'Middlesex'},
    {zip_code: '02145', name: 'Middlesex'},
    {zip_code: '02148', name: 'Middlesex'},
    {zip_code: '02149', name: 'Middlesex'},
    {zip_code: '02150', name: 'Suffolk'},
    {zip_code: '02151', name: 'Suffolk'},
    {zip_code: '02152', name: 'Suffolk'},
    {zip_code: '02153', name: 'Middlesex'},
    {zip_code: '02155', name: 'Middlesex'},
    {zip_code: '02156', name: 'Middlesex'},
    {zip_code: '02163', name: 'Suffolk'},
    {zip_code: '02169', name: 'Norfolk'},
    {zip_code: '02170', name: 'Norfolk'},
    {zip_code: '02171', name: 'Norfolk'},
    {zip_code: '02176', name: 'Middlesex'},
    {zip_code: '02180', name: 'Middlesex'},
    {zip_code: '02184', name: 'Norfolk'},
    {zip_code: '02185', name: 'Norfolk'},
    {zip_code: '02186', name: 'Norfolk'},
    {zip_code: '02187', name: 'Norfolk'},
    {zip_code: '02188', name: 'Norfolk'},
    {zip_code: '02189', name: 'Norfolk'},
    {zip_code: '02190', name: 'Norfolk'},
    {zip_code: '02191', name: 'Norfolk'},
    {zip_code: '02196', name: 'Suffolk'},
    {zip_code: '02199', name: 'Suffolk'},
    {zip_code: '02201', name: 'Suffolk'},
    {zip_code: '02203', name: 'Suffolk'},
    {zip_code: '02204', name: 'Suffolk'},
    {zip_code: '02205', name: 'Suffolk'},
    {zip_code: '02206', name: 'Suffolk'},
    {zip_code: '02210', name: 'Suffolk'},
    {zip_code: '02211', name: 'Suffolk'},
    {zip_code: '02212', name: 'Middlesex'},
    {zip_code: '02215', name: 'Suffolk'},
    {zip_code: '02217', name: 'Suffolk'},
    {zip_code: '02222', name: 'Suffolk'},
    {zip_code: '02238', name: 'Middlesex'},
    {zip_code: '02241', name: 'Suffolk'},
    {zip_code: '02266', name: 'Suffolk'},
    {zip_code: '02269', name: 'Norfolk'},
    {zip_code: '02283', name: 'Suffolk'},
    {zip_code: '02284', name: 'Suffolk'},
    {zip_code: '02293', name: 'Suffolk'},
    {zip_code: '02297', name: 'Suffolk'},
    {zip_code: '02298', name: 'Suffolk'},
    {zip_code: '02301', name: 'Plymouth'},
    {zip_code: '02302', name: 'Plymouth'},
    {zip_code: '02303', name: 'Plymouth'},
    {zip_code: '02304', name: 'Plymouth'},
    {zip_code: '02305', name: 'Plymouth'},
    {zip_code: '02322', name: 'Norfolk'},
    {zip_code: '02324', name: 'Plymouth'},
    {zip_code: '02325', name: 'Plymouth'},
    {zip_code: '02327', name: 'Plymouth'},
    {zip_code: '02330', name: 'Plymouth'},
    {zip_code: '02331', name: 'Plymouth'},
    {zip_code: '02332', name: 'Plymouth'},
    {zip_code: '02333', name: 'Plymouth'},
    {zip_code: '02334', name: 'Bristol'},
    {zip_code: '02337', name: 'Plymouth'},
    {zip_code: '02338', name: 'Plymouth'},
    {zip_code: '02339', name: 'Plymouth'},
    {zip_code: '02340', name: 'Plymouth'},
    {zip_code: '02341', name: 'Plymouth'},
    {zip_code: '02343', name: 'Norfolk'},
    {zip_code: '02344', name: 'Plymouth'},
    {zip_code: '02345', name: 'Plymouth'},
    {zip_code: '02346', name: 'Plymouth'},
    {zip_code: '02347', name: 'Plymouth'},
    {zip_code: '02348', name: 'Plymouth'},
    {zip_code: '02349', name: 'Plymouth'},
    {zip_code: '02350', name: 'Plymouth'},
    {zip_code: '02351', name: 'Plymouth'},
    {zip_code: '02355', name: 'Plymouth'},
    {zip_code: '02356', name: 'Bristol'},
    {zip_code: '02357', name: 'Bristol'},
    {zip_code: '02358', name: 'Plymouth'},
    {zip_code: '02359', name: 'Plymouth'},
    {zip_code: '02360', name: 'Plymouth'},
    {zip_code: '02361', name: 'Plymouth'},
    {zip_code: '02362', name: 'Plymouth'},
    {zip_code: '02364', name: 'Plymouth'},
    {zip_code: '02366', name: 'Plymouth'},
    {zip_code: '02367', name: 'Plymouth'},
    {zip_code: '02368', name: 'Norfolk'},
    {zip_code: '02370', name: 'Plymouth'},
    {zip_code: '02375', name: 'Bristol'},
    {zip_code: '02379', name: 'Plymouth'},
    {zip_code: '02381', name: 'Plymouth'},
    {zip_code: '02382', name: 'Plymouth'},
    {zip_code: '02420', name: 'Middlesex'},
    {zip_code: '02421', name: 'Middlesex'},
    {zip_code: '02445', name: 'Norfolk'},
    {zip_code: '02446', name: 'Norfolk'},
    {zip_code: '02447', name: 'Norfolk'},
    {zip_code: '02451', name: 'Middlesex'},
    {zip_code: '02452', name: 'Middlesex'},
    {zip_code: '02453', name: 'Middlesex'},
    {zip_code: '02454', name: 'Middlesex'},
    {zip_code: '02455', name: 'Middlesex'},
    {zip_code: '02456', name: 'Middlesex'},
    {zip_code: '02457', name: 'Norfolk'},
    {zip_code: '02458', name: 'Middlesex'},
    {zip_code: '02459', name: 'Middlesex'},
    {zip_code: '02460', name: 'Middlesex'},
    {zip_code: '02461', name: 'Middlesex'},
    {zip_code: '02462', name: 'Middlesex'},
    {zip_code: '02464', name: 'Middlesex'},
    {zip_code: '02465', name: 'Middlesex'},
    {zip_code: '02466', name: 'Middlesex'},
    {zip_code: '02467', name: 'Middlesex'},
    {zip_code: '02468', name: 'Middlesex'},
    {zip_code: '02471', name: 'Middlesex'},
    {zip_code: '02472', name: 'Middlesex'},
    {zip_code: '02474', name: 'Middlesex'},
    {zip_code: '02475', name: 'Middlesex'},
    {zip_code: '02476', name: 'Middlesex'},
    {zip_code: '02477', name: 'Middlesex'},
    {zip_code: '02478', name: 'Middlesex'},
    {zip_code: '02479', name: 'Middlesex'},
    {zip_code: '02481', name: 'Norfolk'},
    {zip_code: '02482', name: 'Norfolk'},
    {zip_code: '02492', name: 'Norfolk'},
    {zip_code: '02493', name: 'Middlesex'},
    {zip_code: '02494', name: 'Norfolk'},
    {zip_code: '02495', name: 'Middlesex'},
    {zip_code: '02532', name: 'Barnstable'},
    {zip_code: '02534', name: 'Barnstable'},
    {zip_code: '02535', name: 'Dukes'},
    {zip_code: '02536', name: 'Barnstable'},
    {zip_code: '02537', name: 'Barnstable'},
    {zip_code: '02538', name: 'Plymouth'},
    {zip_code: '02539', name: 'Dukes'},
    {zip_code: '02540', name: 'Barnstable'},
    {zip_code: '02541', name: 'Barnstable'},
    {zip_code: '02542', name: 'Barnstable'},
    {zip_code: '02543', name: 'Barnstable'},
    {zip_code: '02552', name: 'Dukes'},
    {zip_code: '02553', name: 'Barnstable'},
    {zip_code: '02554', name: 'Nantucket'},
    {zip_code: '02556', name: 'Barnstable'},
    {zip_code: '02557', name: 'Dukes'},
    {zip_code: '02558', name: 'Plymouth'},
    {zip_code: '02559', name: 'Barnstable'},
    {zip_code: '02561', name: 'Barnstable'},
    {zip_code: '02562', name: 'Barnstable'},
    {zip_code: '02563', name: 'Barnstable'},
    {zip_code: '02564', name: 'Nantucket'},
    {zip_code: '02568', name: 'Dukes'},
    {zip_code: '02571', name: 'Plymouth'},
    {zip_code: '02574', name: 'Barnstable'},
    {zip_code: '02575', name: 'Dukes'},
    {zip_code: '02576', name: 'Plymouth'},
    {zip_code: '02584', name: 'Nantucket'},
    {zip_code: '02601', name: 'Barnstable'},
    {zip_code: '02630', name: 'Barnstable'},
    {zip_code: '02631', name: 'Barnstable'},
    {zip_code: '02632', name: 'Barnstable'},
    {zip_code: '02633', name: 'Barnstable'},
    {zip_code: '02634', name: 'Barnstable'},
    {zip_code: '02635', name: 'Barnstable'},
    {zip_code: '02637', name: 'Barnstable'},
    {zip_code: '02638', name: 'Barnstable'},
    {zip_code: '02639', name: 'Barnstable'},
    {zip_code: '02641', name: 'Barnstable'},
    {zip_code: '02642', name: 'Barnstable'},
    {zip_code: '02643', name: 'Barnstable'},
    {zip_code: '02644', name: 'Barnstable'},
    {zip_code: '02645', name: 'Barnstable'},
    {zip_code: '02646', name: 'Barnstable'},
    {zip_code: '02647', name: 'Barnstable'},
    {zip_code: '02648', name: 'Barnstable'},
    {zip_code: '02649', name: 'Barnstable'},
    {zip_code: '02650', name: 'Barnstable'},
    {zip_code: '02651', name: 'Barnstable'},
    {zip_code: '02652', name: 'Barnstable'},
    {zip_code: '02653', name: 'Barnstable'},
    {zip_code: '02655', name: 'Barnstable'},
    {zip_code: '02657', name: 'Barnstable'},
    {zip_code: '02659', name: 'Barnstable'},
    {zip_code: '02660', name: 'Barnstable'},
    {zip_code: '02661', name: 'Barnstable'},
    {zip_code: '02662', name: 'Barnstable'},
    {zip_code: '02663', name: 'Barnstable'},
    {zip_code: '02664', name: 'Barnstable'},
    {zip_code: '02666', name: 'Barnstable'},
    {zip_code: '02667', name: 'Barnstable'},
    {zip_code: '02668', name: 'Barnstable'},
    {zip_code: '02669', name: 'Barnstable'},
    {zip_code: '02670', name: 'Barnstable'},
    {zip_code: '02671', name: 'Barnstable'},
    {zip_code: '02672', name: 'Barnstable'},
    {zip_code: '02673', name: 'Barnstable'},
    {zip_code: '02675', name: 'Barnstable'},
    {zip_code: '02702', name: 'Bristol'},
    {zip_code: '02703', name: 'Bristol'},
    {zip_code: '02712', name: 'Bristol'},
    {zip_code: '02713', name: 'Dukes'},
    {zip_code: '02714', name: 'Bristol'},
    {zip_code: '02715', name: 'Bristol'},
    {zip_code: '02717', name: 'Bristol'},
    {zip_code: '02718', name: 'Bristol'},
    {zip_code: '02719', name: 'Bristol'},
    {zip_code: '02720', name: 'Bristol'},
    {zip_code: '02721', name: 'Bristol'},
    {zip_code: '02722', name: 'Bristol'},
    {zip_code: '02723', name: 'Bristol'},
    {zip_code: '02724', name: 'Bristol'},
    {zip_code: '02725', name: 'Bristol'},
    {zip_code: '02726', name: 'Bristol'},
    {zip_code: '02738', name: 'Plymouth'},
    {zip_code: '02739', name: 'Plymouth'},
    {zip_code: '02740', name: 'Bristol'},
    {zip_code: '02741', name: 'Bristol'},
    {zip_code: '02742', name: 'Bristol'},
    {zip_code: '02743', name: 'Bristol'},
    {zip_code: '02744', name: 'Bristol'},
    {zip_code: '02745', name: 'Bristol'},
    {zip_code: '02746', name: 'Bristol'},
    {zip_code: '02747', name: 'Bristol'},
    {zip_code: '02748', name: 'Bristol'},
    {zip_code: '02760', name: 'Bristol'},
    {zip_code: '02761', name: 'Bristol'},
    {zip_code: '02762', name: 'Norfolk'},
    {zip_code: '02763', name: 'Bristol'},
    {zip_code: '02764', name: 'Bristol'},
    {zip_code: '02766', name: 'Bristol'},
    {zip_code: '02767', name: 'Bristol'},
    {zip_code: '02768', name: 'Bristol'},
    {zip_code: '02769', name: 'Bristol'},
    {zip_code: '02770', name: 'Plymouth'},
    {zip_code: '02771', name: 'Bristol'},
    {zip_code: '02777', name: 'Bristol'},
    {zip_code: '02779', name: 'Bristol'},
    {zip_code: '02780', name: 'Bristol'},
    {zip_code: '02783', name: 'Bristol'},
    {zip_code: '02790', name: 'Bristol'},
    {zip_code: '02791', name: 'Bristol'},
    {zip_code: '05501', name: 'Essex'},
    {zip_code: '05544', name: 'Essex'}
])

categories = Category.create([
    {"name": "Software Developer"},
    {"name": "System Architect"}
])

locations = Location.create([
    {
        "name":"Boston Data Group",
        "street_address_1":"1600 Providence Hwy",
        "street_address_2":"Suite 123",
        "city":"Walpole",
        "state":"MA",
        "zip_code":"02081"
    },
    {
        "name":"Test",
        "street_address_1":"BELC-275-14",
        "street_address_2":"",
        "city":"Belchertown",
        "state":"MA",
        "zip_code":"01007"
    },
    {
        "name":"Freedom Fertility Pharmacy",
        "street_address_1":"12 Kent Way",
        "street_address_2":"",
        "city":"Byfield",
        "state":"MA",
        "zip_code":"01922"
    },
    {
        "name": "Trimark USA",
        "street_address_1": "505 Collins St",
        "street_address_2": "", 
        "city": "Attleboro", 
        "state": "MA",
        "zip_code": "02703"
    }
])

posters = JobPoster.create([{"id":1,"first_name":"Jonathan", "last_name":"De Jesus"}])

jobs = JobPosting.create([
    {
        "title":"Full Stack Java Developer",
        "status":0,
        "description":"Summary:\r\n\r\nBoston Data Group seeks strong Full-Stack Java Developer to develop, maintain and design enterprise applications. The qualified candidate will be a highly driven, quick learner, with excellent communication and a proven leader.  The ideal candidate will enjoy the opportunity to further developing their skills in a productive, challenging, and creative environment. Must have experience developing web applications with responsive web design and a java backend using Web services, Rest API’s, Micro Services, AngularJS/ReactJS and Oracle database.\r\n\r\n Responsibilities:\r\n\r\nDesign, implement and maintain Enterprise applications built using Java, AngularJS, Oracle and frameworks\r\nResolve complex defects during testing\r\nCreate technical design and implementation documents\r\nHelp maintain code quality through code reviews, design patterns\r\nProvide guidance on intended solution and best practices during intake, development configuration and testing phase\r\nCollaborate with core team to manage support application\r\n Requirements:\r\n\r\n5+ years of development experience\r\n3+ years demonstrated real world experience in Enterprise Web Application development, Object Oriented languages such as Java or C++\r\nSoftware engineering principles such as software design patterns, Database principles such as Oracle, MongDB, Hadoop, etc.\r\nKnowledge and experience in Rest API design and implementation\r\nStrong JavaScript framework experience such as AngularJS, ReactJS\r\nExperience with mobile development a plus\r\nBasic knowledge of Continuous Integration/Continuous Deployment and DevOps principles\r\nFamiliarity with Agile is preferred",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(1),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Junior Front End Developer",
        "status":1,
        "description":"Test",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(2),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Senior Database Architect",
        "status":2,
        "description":"As a Senior Data Architect at Teradata, you will participate in complex, multi-disciplinary projects related to the Teradata Analytics platform. The Teradata Analytics Platform team is an IT organization chartered to utilize Teradata products and services to deliver information and analytic capabilities to all Teradata business functions and external stakeholders. As an IT Data Architect, you will be responsible for developing and maintaining a formal description of Teradata data and data structures using logical and physical data models. The Data Architect is responsible for developing and enforcing data modeling standards and best practices, managing the enterprise data model and managing all metadata in the Teradata Analytics Platform environment. The Data Architect role is broader than the role of a typical application level “data modeler” in that it involves identifying the data needs, providing guidance on how to extract, transform and load the data and integrating the new data and applications with master data and other existing data in the Teradata Analytics Platform. It also involves modeling from a neutral perspective rather than from a single business functional perspective Role and ResponsibilitiesQualifications ",
        "category": Category.find_by_id(2),
        "location": Location.find_by_id(3),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Web Designer",
        "status":1,
        "description":"TriMark USA is looking for an energetic and highly motivated person to fill the new role of Web Designer / Developer. ",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(4),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Full Stack Java Developer",
        "status":0,
        "description":"Summary:\r\n\r\nBoston Data Group seeks strong Full-Stack Java Developer to develop, maintain and design enterprise applications. The qualified candidate will be a highly driven, quick learner, with excellent communication and a proven leader.  The ideal candidate will enjoy the opportunity to further developing their skills in a productive, challenging, and creative environment. Must have experience developing web applications with responsive web design and a java backend using Web services, Rest API’s, Micro Services, AngularJS/ReactJS and Oracle database.\r\n\r\n Responsibilities:\r\n\r\nDesign, implement and maintain Enterprise applications built using Java, AngularJS, Oracle and frameworks\r\nResolve complex defects during testing\r\nCreate technical design and implementation documents\r\nHelp maintain code quality through code reviews, design patterns\r\nProvide guidance on intended solution and best practices during intake, development configuration and testing phase\r\nCollaborate with core team to manage support application\r\n Requirements:\r\n\r\n5+ years of development experience\r\n3+ years demonstrated real world experience in Enterprise Web Application development, Object Oriented languages such as Java or C++\r\nSoftware engineering principles such as software design patterns, Database principles such as Oracle, MongDB, Hadoop, etc.\r\nKnowledge and experience in Rest API design and implementation\r\nStrong JavaScript framework experience such as AngularJS, ReactJS\r\nExperience with mobile development a plus\r\nBasic knowledge of Continuous Integration/Continuous Deployment and DevOps principles\r\nFamiliarity with Agile is preferred",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(2),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Junior Front End Developer",
        "status":1,
        "description":"Test",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(4),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Senior Database Architect",
        "status":2,
        "description":"As a Senior Data Architect at Teradata, you will participate in complex, multi-disciplinary projects related to the Teradata Analytics platform. The Teradata Analytics Platform team is an IT organization chartered to utilize Teradata products and services to deliver information and analytic capabilities to all Teradata business functions and external stakeholders. As an IT Data Architect, you will be responsible for developing and maintaining a formal description of Teradata data and data structures using logical and physical data models. The Data Architect is responsible for developing and enforcing data modeling standards and best practices, managing the enterprise data model and managing all metadata in the Teradata Analytics Platform environment. The Data Architect role is broader than the role of a typical application level “data modeler” in that it involves identifying the data needs, providing guidance on how to extract, transform and load the data and integrating the new data and applications with master data and other existing data in the Teradata Analytics Platform. It also involves modeling from a neutral perspective rather than from a single business functional perspective Role and ResponsibilitiesQualifications ",
        "category": Category.find_by_id(2),
        "location": Location.find_by_id(2),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Web Designer",
        "status":1,
        "description":"TriMark USA is looking for an energetic and highly motivated person to fill the new role of Web Designer / Developer. ",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(4),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Junior Front End Developer",
        "status":1,
        "description":"Test",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(3),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Senior Database Architect",
        "status":2,
        "description":"As a Senior Data Architect at Teradata, you will participate in complex, multi-disciplinary projects related to the Teradata Analytics platform. The Teradata Analytics Platform team is an IT organization chartered to utilize Teradata products and services to deliver information and analytic capabilities to all Teradata business functions and external stakeholders. As an IT Data Architect, you will be responsible for developing and maintaining a formal description of Teradata data and data structures using logical and physical data models. The Data Architect is responsible for developing and enforcing data modeling standards and best practices, managing the enterprise data model and managing all metadata in the Teradata Analytics Platform environment. The Data Architect role is broader than the role of a typical application level “data modeler” in that it involves identifying the data needs, providing guidance on how to extract, transform and load the data and integrating the new data and applications with master data and other existing data in the Teradata Analytics Platform. It also involves modeling from a neutral perspective rather than from a single business functional perspective Role and ResponsibilitiesQualifications ",
        "category": Category.find_by_id(2),
        "location": Location.find_by_id(1),
        "job_poster": JobPoster.find_by_id(1)
    },
    {
        "title":"Web Designer",
        "status":1,
        "description":"TriMark USA is looking for an energetic and highly motivated person to fill the new role of Web Designer / Developer. ",
        "category": Category.find_by_id(1),
        "location": Location.find_by_id(3),
        "job_poster": JobPoster.find_by_id(1)
    }
])